export const landAnimals = [
  { name: "Mouse", color: "gray", biome: "land", evolveScore: 0 },
  { name: "Rabbit", color: "pink", biome: "land", evolveScore: 5 },
  { name: "Pig", color: "brown", biome: "land", evolveScore: 15 },
  { name: "Deer", color: "tan", biome: "land", evolveScore: 30 },
  { name: "Fox", color: "orange", biome: "land", evolveScore: 50 },
  { name: "Wolf", color: "lightgray", biome: "land", evolveScore: 70 },
  { name: "Lion", color: "goldenrod", biome: "land", evolveScore: 100 },
  { name: "Bear", color: "#654321", biome: "land", evolveScore: 130 },
  { name: "Crocodile", color: "green", biome: "land", evolveScore: 160 },
  { name: "Rhino", color: "gray", biome: "land", evolveScore: 200 },
  { name: "Elephant", color: "lightgray", biome: "land", evolveScore: 250 },
  { name: "Mammoth", color: "#70543E", biome: "land", evolveScore: 300 },
  { name: "Saber Tooth", color: "#8B4513", biome: "land", evolveScore: 350 },
  { name: "T-Rex", color: "darkgreen", biome: "land", evolveScore: 400 },
  { name: "Dragon", color: "red", biome: "land", evolveScore: 500 },
];
